package schema

import (
	"fmt"
	"strings"
	"time"

	// Packages
	uuid "github.com/google/uuid"
	pg "github.com/mutablelogic/go-pg"
)

////////////////////////////////////////////////////////////////////////////////
// TYPES

type UsageType string

type UsageMeta struct {
	InputTokens      uint            `json:"input_tokens,omitempty" help:"Number of input tokens consumed by the request" example:"18"`
	OutputTokens     uint            `json:"output_tokens,omitempty" help:"Number of output tokens generated by the model" example:"12"`
	CacheReadTokens  uint            `json:"cache_read_tokens,omitempty" help:"Number of tokens read from cache" example:"5"`
	CacheWriteTokens uint            `json:"cache_write_tokens,omitempty" help:"Number of tokens written to cache" example:"3"`
	ReasoningTokens  uint            `json:"reasoning_tokens,omitempty" help:"Number of tokens used for reasoning" example:"2"`
	Meta             ProviderMetaMap `json:"meta,omitempty" help:"Optional provider-specific metadata for usage records" optional:""`
}

type UsageInsert struct {
	Type      UsageType `json:"type,omitempty" help:"Usage category" example:"ask"`
	Batch     *string   `json:"batch,omitempty" help:"Optional batch identifier for batch operations" optional:""`
	User      uuid.UUID `json:"user,omitempty" help:"Optional user ID for attribution" optional:""`
	Session   uuid.UUID `json:"session,omitempty" help:"Optional session ID for chat interactions" optional:""`
	Provider  *string   `json:"provider,omitempty" help:"Optional provider name for attribution" optional:""`
	Model     string    `json:"model,omitempty" help:"Model name associated with the usage record" example:"gemini-2.5-pro"`
	UsageMeta `embed:""`
}

type Usage struct {
	ID          uint64 `json:"id,omitempty" help:"Usage record identifier" readonly:""`
	UsageInsert `embed:""`
	CreatedAt   time.Time `json:"created_at,omitempty" help:"Creation timestamp" readonly:""`
}

////////////////////////////////////////////////////////////////////////////////
// GLOBALS

const (
	UsageTypeEmbedding UsageType = "embedding"
	UsageTypeAsk       UsageType = "ask"
	UsageTypeChat      UsageType = "chat"
)

////////////////////////////////////////////////////////////////////////////////
// PUBLIC METHODS - READER

func (u *Usage) Scan(row pg.Row) error {
	var sessionID *uuid.UUID
	var userID *uuid.UUID

	if err := row.Scan(
		&u.ID, &u.Type, &u.Batch, &sessionID, &userID, &u.Provider, &u.Model, &u.InputTokens,
		&u.OutputTokens, &u.CacheReadTokens, &u.CacheWriteTokens, &u.ReasoningTokens,
		&u.Meta, &u.CreatedAt,
	); err != nil {
		return err
	}
	if sessionID != nil {
		u.Session = *sessionID
	} else {
		u.Session = uuid.Nil
	}
	if userID != nil {
		u.User = *userID
	} else {
		u.User = uuid.Nil
	}
	if u.Meta == nil {
		u.Meta = make(ProviderMetaMap)
	}
	return nil
}

////////////////////////////////////////////////////////////////////////////////
// PUBLIC METHODS - WRITER

func (u UsageInsert) Insert(bind *pg.Bind) (string, error) {
	usageType, err := normalizeUsageType(u.Type)
	if err != nil {
		return "", err
	} else {
		bind.Set("type", usageType)
	}

	model := strings.TrimSpace(u.Model)
	if model == "" {
		return "", ErrBadParameter.With("usage model is required")
	} else {
		bind.Set("model", model)
	}

	if u.Batch != nil && strings.TrimSpace(*u.Batch) != "" {
		bind.Set("batch", strings.TrimSpace(*u.Batch))
	} else {
		bind.Set("batch", nil)
	}

	if u.Session == uuid.Nil {
		bind.Set("session", nil)
	} else {
		bind.Set("session", u.Session)
	}

	if u.Provider != nil && strings.TrimSpace(*u.Provider) != "" {
		bind.Set("provider", strings.TrimSpace(*u.Provider))
	} else {
		bind.Set("provider", nil)
	}

	if u.User == uuid.Nil {
		bind.Set("user", nil)
	} else {
		bind.Set("user", u.User)
	}
	bind.Set("input_tokens", u.InputTokens)
	bind.Set("output_tokens", u.OutputTokens)
	bind.Set("cache_read_tokens", u.CacheReadTokens)
	bind.Set("cache_write_tokens", u.CacheWriteTokens)
	bind.Set("reasoning_tokens", u.ReasoningTokens)

	if u.Meta == nil {
		bind.Set("meta", make(ProviderMetaMap))
	} else {
		bind.Set("meta", u.Meta)
	}

	return bind.Query("usage.insert"), nil
}

func (u UsageInsert) Update(_ *pg.Bind) error {
	return fmt.Errorf("UsageInsert: update: not supported")
}

////////////////////////////////////////////////////////////////////////////////
// PRIVATE METHODS

func normalizeUsageType(value UsageType) (UsageType, error) {
	switch value {
	case UsageTypeAsk, UsageTypeChat, UsageTypeEmbedding:
		return value, nil
	default:
		return "", ErrBadParameter.Withf("invalid usage type %q", value)
	}
}
